Consensys/linea-constraints

- Makefile
- txndata/constants.lisp
- txndata/constraints.lisp
I'll put TXN_DATA in teh Makefile again after updating the tracing
> feat(txn-data): implement max nonce comparaison

- hub/constraints/tx_init/constraints.lisp
- hub/constraints/tx_skip/constraints.lisp
Reject transactions from senders with deployed code.
> Implement EIP 3607

- exp/constraints.lisp
https://veridise.notion.site/Magic-number-should-be-replaced-with-CT_MAX_CMPTN_MODEXP_LOG-constant-182404a228cb40f4943b784f0dca57db
> fix(exp): use CT_MAX_CMPTN_MODEXP_LOG

- Makefile
removed `GAS` from both `ZKEVM_MODULES` modules files
> Remove `GAS` from `ZKEVM_MODULES` and `ZKEVM_MODULES_FOR_REFERENCE_TESTS`

- ecdata/constraints.lisp
https://veridise.notion.site/No-counter-constancy-on-NOT_ON_G2-and-NOT_ON_G2_ACC-cb2ca4f153d54f2b9147a2688f55a700
> fix(ecdata): add counter constancy on NOT_ON_G2 and NOT_ON_G2_ACC

- bin/constraints.lisp
The oreconditions was already removed from the spec, so the lisp was just a previous spec implem ...
> fix(BIN): remove unnecessary preconditions

- rlptxn/constants.lisp
- rlptxn/constraints.lisp
spec : https://github.com/Consensys/linea-specification-internal/pull/620 & https://github.com/Consensys/linea-specification-internal/pull/618
> fix(rlpTxn): constraint ADDR during AccessList tuple & ChainId

- oob/constraints.lisp
implem of the spec : https://github.com/Consensys/linea-specification-internal/pull/636
> clean(OOB): delete binary dupliacte constraints + from `call_gas` to `callee_gas`

- mxp/constraints.lisp
https://www.notion.so/veridise/Missing-constancy-constraints-in-MXP-7bf35cf362b34b6b83c50200914fc7ab
> fix(mxp): add constancy constraints for CN and DEPLOYS

- hub/constraints/instruction-handling/acc.lisp
https://veridise.notion.site/EXTCODESIZE-returns-incorrect-size-during-deployment-10e105edf1db80c3a6eac073fb565ab7
> Fix value constraints for EXTCODESIZE / EXTCODECOPY

- constants/constants.lisp
https://veridise.notion.site/Incorrect-refund-constants-105105edf1db807086c5f5a38571badb
> fix(constants): correct refund constants

- hub/constraints/tx_init/constraints.lisp
- hub/constraints/tx_skip/constraints.lisp
This PR fixes typos from #430.
> Add missing _NEW's to TX_INIT and TX_SKIP sections

- hub/constraints/instruction-handling/acc.lisp
- more shorthands, fewer `[ stack/DEC_FLAG k ]`'s and `[ stack/STACK_ITEM_VALUE k ]`'s
- boolean flag per instruction
- using the `account-instruction---bla` convention
- named constants for row offsets
- splitting of some constraints
- force `account/ROM_LEX_FLAG = 0` whenever possible
- changed the `NSR` of instructions that touch a current account (`CODESIZE`, `SELFBALANCE`)
- **Bug-fix:** `SELFBALANCE` was receiving the wrong value
- **Bug-fix:** several shorthands were missing `shift`'s ... !
> Typo and bug fixes for the `ACC` instruction family

- ecdata/constraints.lisp
- hub/constraints/instruction-handling/jump.lisp
- hub/constraints/instruction-handling/log.lisp
These are no longer necessary because the relevant bug in `corset` has been fixed already.
> Remove `(vanishes! 0)`

- hub/constraints/instruction-handling/jump.lisp
- hub/constraints/instruction-handling/log.lisp
Likely the aftermath of having erased some of the `(vanishes! 0)` constraints and having left the `(begin ...` stuff.
> Make the constraints compile again

- hub/constraints/instruction-handling/halting/selfdestruct.lisp
> `SELFDESTRUCT` typo fix

- hub/constraints/instruction-handling/copy/codecopy.lisp
The sanity check constraints only apply to **unexceptional** CODECOPY instructions.
> CODECOPY sanity check fix

- hub/constraints/instruction-handling/create/constraints/deployment-failures.lisp
- hub/constraints/instruction-handling/create/constraints/reverting-one-step.lisp
- hub/constraints/instruction-handling/create/constraints/reverting-two-step.lisp
- hub/constraints/instruction-handling/halting/return.lisp
- mmu/instructions/invalid_code_prefix.lisp
Specified in https://github.com/Consensys/linea-specification/pull/29
> Remove double negative from `ICPX` transfer `HUB -> MMU`

- hub/constraints/instruction-handling/call/precompiles/ec_add_mul_pairing/success_case.lisp
Around page 326
The shorthand uses the PRC flags directly, not their "nontrivial" counterparts.
> Fixed divergence from spec in the "return data size" macro for `ECADD`/`ECMUL`/`ECPAIRING`

- hub/constraints/instruction-handling/acc.lisp
Implements https://github.com/Consensys/linea-specification/pull/38
> Only unexceptional `ACCOUNT` instructions that `touchForeignAddress` update its warmth

- hub/constraints/instruction-handling/copy/generalities.lisp
Implements https://github.com/Consensys/linea-specification/pull/40
> `EXTCODECOPY` requires the `CFI` as its `MMU_SRC_ID` only for addresses not currently under deployment

- Makefile
- bin/lookups/bin_into_binreftable.lisp
- blockdata/constants-ethereum.lisp
- blockdata/constants-linea.lisp
- blockdata/processing/gaslimit/ethereum.lisp
- blockdata/processing/gaslimit/linea.lisp
- ecdata/constraints.lisp
- hub/columns/stack.lisp
- hub/constraints/account.lisp
- hub/constraints/instruction-handling/call/generalities/universal.lisp
- hub/constraints/instruction-handling/call/triggers.lisp
- hub/constraints/instruction-handling/halting/selfdestruct.lisp
- hub/constraints/stack_patterns.lisp
- hub/lookups/hub_into_rom_instruction_fetching.lisp
- logdata/lookups/logdata-to-rlprcpt.lisp
- loginfo/lookups/loginfo-into-logdata.lisp
- rlptxn/constraints.lisp
- rom/constraints.lisp
- shf/constraints.lisp
- txndata/constraints.lisp
This adds support for a new build target, namely `zkevm.go.bin`.  This target is built using `go-corset` rather than the original `corset` tool.  In order to make this work, a very small number of fixes to the constraints were required.  These consist of simple typos and/or broken debug constraints.
> feat: enable build for `zkevm.go.bin`

- blockhash/constants.lisp
- blockhash/constraints.lisp
This avoids dealing with negative constants.
> Replace `NEGATIVE_OF_BLOCKHASH` with a `(defun ...)` expression

- blockhash/constraints.lisp
This refactors the function `negative-of-blockhash-depth` to be a `defpurefun` instead of simply a `defun`.
> fix: refactor `negative-of-blockhash-depth`

- .github/workflows/check.yml
This swaps out the Rust `corset` tool for the new `go-corset` tool in the CI build.  This will help to ensure that the constraints always compile with `go-corset`.
> feat: swap `corset` for `go-corset` on CI build

- Makefile
This now embeds two pieces of metadata with every zkevm.bin built (likewise for zkevm_for_reference_tests.bin).  Specifically, it embeds the git commit of the enclosing repository and also a timestamp.
> feat: support embedding metadata

- Makefile
This stores any tags on the current commit into the zkevm.bin metadata. Thus, for a tagged release, the tag (or tags if there are more than one) will be available in the metadata.
> feat: include current tag(s) in zkevm.bin metadata

- hub/constraints/consistency/account/columns.lisp
- hub/constraints/consistency/account/constraints.lisp
Implementation of https://github.com/Consensys/linea-specification/pull/97
> Reintroduce `acp_EXISTS` / `acp_EXISTS_NEW` columns for state manager

- .github/workflows/check.yml
- bin/constraints.lisp
- euc/constraints.lisp
- hub/lookups/helpers.lisp
- hub/lookups/hub_into_add.lisp
- hub/lookups/hub_into_bin.lisp
- hub/lookups/hub_into_exp.lisp
- hub/lookups/hub_into_ext.lisp
- hub/lookups/hub_into_mmu.lisp
- hub/lookups/hub_into_mod.lisp
- hub/lookups/hub_into_mul.lisp
- hub/lookups/hub_into_mxp.lisp
- hub/lookups/hub_into_oob.lisp
- hub/lookups/hub_into_rlp_addr.lisp
- hub/lookups/hub_into_rom_jump_destination_vetting.lisp
- hub/lookups/hub_into_rom_lex.lisp
- hub/lookups/hub_into_shf.lisp
- hub/lookups/hub_into_trm.lisp
- hub/lookups/hub_into_wcp.lisp
- wcp/constraints.lisp
This is another simple prestep before upgrading to `go-corset` version `1.1`.  This simply removes `and` which will no longer exist in `go-corset` version `1.1` and replaces it with `*` (which, in fact, is exactly how it is currently defined).
**NOTE**: I have compared the `zkevm.bin` before and after this PR --- there are only a small number of trivial differences.  See attached diff: [zkevm.df5a3474c7.diff.txt](https://github.com/user-attachments/files/19575895/zkevm.df5a3474c7.diff.txt)
> feat: another pre step before go-corset version 1.1

- .github/workflows/check.yml
- .gitignore
- Makefile
- hub/london/columns/miscellaneous.lisp
When modules need to be fork dependent, structure is : folder with the name of the module and then subfolders with the names of the forks, like so 
Makefile command lines added to generate one bin file per fork 
- `zkevm_london.bin`
- `zkevm_shanghai.bin`
These bin files are generated using common modules and fork specific ones 
Co-authored by: DavePearce <dave01001110@gmail.com>
> feat: Makefile change for one zkevm bin per fork

- Makefile
Fixes a potential shell globbing issue in the Makefile by adding quotes around the wildcard pattern in the find command. Without quotes, the shell might expand the pattern before the find command is executed, leading to unexpected behavior if there are matching files in the current directory. This is a standard best practice for shell commands in Makefiles
> fix: Add quotes around wildcard pattern in find command
